.\"
.\" Copyright (c) 2005-2006 Alon Bar-Lev <alon.barlev@gmail.com>
.\" All rights reserved.
.\"
.\" This program is free software; you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License version 2
.\" as published by the Free Software Foundation.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program (see the file COPYING.GPL included with this
.\" distribution); if not, write to the Free Software Foundation, Inc.,
.\" 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
.\"
.\" Generate by:
.\" $ groff -mdoc -Tascii pkcs11-data.1
.\"
.\" Always put argument after .Nm (otherwise man2html breaks)
.\"
.Dd December 1, 2006
.Os POSIX-compatible
.Dt pkcs11-data 1
.Sh NAME
.Nm pkcs11-data
.Nd Data object PKCS#11 enabled token manipulator
.Sh SYNOPSIS
.Nm pkcs11-data
.Op --verbose
.Op --add-provider
.Op --public
.Op --token-wait
.Op --cmd
.Sh DESCRIPTION
.Nm pkcs11-data
pkcs11-data provides a simple interface to manipulate data on cryptographic
providers by using
RSA Security Inc. PKCS#11 Cryptographic Token Interface (Cryptoki).
The following options are available:
.Bl -tag -width "AA"
.It --verbose
Enable logging.
.It --add-provider
Add PKCS#11 provider, this option can be specified more than once.
.It --public
Data object in on public section.
.It --token-wait
Wait for token until it inserted.
.It --cmd
Command to execute:
.Bl -tag -width "RECOVER" -compact
.It tokens
List available token ids.
.It list
.Op --token
.
List available data objects.
.It export
.Op [--token]
.Op --application
.Op --label
.Op [--file]
.Op [ --application --label --file ]
.
Export data object content from specific token to a file or
to standard output. Several objects can be exported at one execution.
.It import
.Op --token
.Op --application
.Op --label
.Op [--file]
.
Import data object content to a specific token from a file or from
standard input.
.It remove
.Op --token
.Op --application
.Op --label
.
Remove data object.
.El
.El
.Sh AUTHORS AND COPYRIGHT
Copyright (c) 2006 Alon Bar-Lev <alon.barlev@gmail.com>
.Pp
All rights reserved.
.Pp
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
